FROM python:3.9-alpine
RUN apk update
RUN apk add py-gunicorn postgresql-dev gcc python3-dev musl-dev
# Upgrade pip 
RUN python3 -m pip install --upgrade pip
RUN python -m venv /venv
COPY ./requirements.txt /
RUN . venv/bin/activate && python3 -m pip install psycopg2 && python -m pip install -r requirements.txt
COPY ./app /app
ENV FLASK_APP=app
ENV VIRTUAL_ENV=/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
COPY ./docker/config /config
COPY ./docker/docker_entrypoint.sh /
RUN chmod +x /docker_entrypoint.sh
WORKDIR /
EXPOSE 30000

ENTRYPOINT [ "./docker_entrypoint.sh" ]
CMD [ "/venv/bin/gunicorn", "-c", "python:config.gunicorn", "app.app:app" ]