pipeline:
  migration:
    image: ubuntu:latest
    when:
      path:
        include: ['.woodpecker/.database-migration.yml', 'database/sql/*.sql']
    environment:
      - DB_SSL_MODE=require
      - DB_SSL=true
      - DB_ROOT_CERT_PATH=/tmp/.postgresql/root.crt
      - FLYWAY_VERSION=8.5.0
    commands:
      - curl --create-dirs -o /tmp/.postgresql/root.crt -O ${{ secrets.DB_CERT_URL }}
      - wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-${FLYWAY_VERSION}/flyway /usr/local/bin
      - cd database
      - flyway info
      - flyway migrate
      - flyway info
    secrets: [ DB_PASSWORD, DB_USERNAME, DB_NAME, DB_HOST ]
  
