name: Lint and Build

on: push

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        python -m pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --fail-under=9 app
    - name: Testing the code with pytest
      run: |
        python -m pytest
  docker:
    needs: pylint
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: simcax/dotime:${{ secrets.MAJOR_VERSION }}.${{ secrets.FEATURE_VERSION }}.${{ github.run_number}}
  updateDeployRepo:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        name: simcax/deploy-dotime.me
        token: ${{ secrets.DEPLOY_DOTIME_TOKEN }}
    - name: Update image tag in deploy 
      run: |
        python3 update-yaml-version.py dotime-me/values.yaml ${{ secrets.MAJOR_VERSION }}.${{ secrets.FEATURE_VERSION }}.${{ github.run_number}}
        git config --global user.name "Carsten Skov"
        git config --global user.email "carsten@simcax.dk"
        git commit -am "Bump image tag to ${{ secrets.MAJOR_VERSION }}.${{ secrets.FEATURE_VERSION }}.${{ github.run_number}}"
        git push

    